version: '3.4'

services:
  backend:
    image: gitlab.progmasters.hu:4567/fort.zsuzsanna/angular-moovsmart/backend-prod
    environment: 
      - SPRING_PROFILES_ACTIVE=production
      - FRONTEND_HOST=moovsmart.progmasters.hu
    ports:
      - "8080:8080"
    network_mode: host
      
  frontend:
    image: gitlab.progmasters.hu:4567/fort.zsuzsanna/angular-moovsmart/frontend-prod
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ssl_certs:/etc/letsencrypt/live/ohhaithere.com/fullchain.pem
    network_mode: host
