version: '3.4'

services:
  backend:
    image: gitlab.progmasters.hu:4567/fort.zsuzsanna/angular-moovsmart/backend-prod
    environment: 
      - SPRING_PROFILES_ACTIVE=development
    ports:
      - 8080:8080
    network_mode: "host" 
      
  frontend:
    image: gitlab.progmasters.hu:4567/fort.zsuzsanna/angular-moovsmart/frontend-prod
    ports: 
      - 80:80
    links:
      - backend  
