spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moovsmart?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234

mailing-address: http://localhost:8080/api/users/activate/
