spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moovsmart?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234

cors-policies: http://34.254.251.78, http://moovsmart-demo.progmasters.hu
